src/clinica/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# from django.shortcuts import render


# def base(request):
#     # return render(request, "test.html")
#     return render(request, "login.html")


urlpatterns = [
    # url(r'^/', base),
    url(r'^admin/', admin.site.urls),
    url(r'^paciente/', include('paciente.urls', namespace='paciente')),
]

src/paciente/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [

    url(r'^paciente/create/$', views.CreateView.as_view(), name='paciente_create'),
    url(r'^paciente/update/(?P<pk>[0-9]+)/$', views.UpdateView.as_view(), name='paciente_update'),
    url(r'^paciente/delete/(?P<pk>[0-9]+)/$', views.DeleteView.as_view(), name='paciente_delete'),
    url(r'^paciente/$', views.ListView.as_view(), name='paciente_list'),

]

src/paciente/models.py
from django.db import models

from medico.models import Prevision
from . import manager

# Create your models here.
class Paciente(models.Model):
    rut = models.CharField(max_length=10, unique=True)
    nombre = models.CharField(max_length=100, null=False, blank=False)
    apellido_p = models.CharField(max_length=50, null=False, blank=False)
    apellido_m = models.CharField(max_length=50, default='S/A')
    fecha_nacimiento = models.DateField(auto_now_add=False, auto_now=False)
    fono = models.CharField(max_length=9)
    domicilio = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)
    prevision = models.ForeignKey(Prevision)

    objects = manager.PacienteManager()

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

src/paciente/forms.py
from django import forms

from utils.forms import UtilForm
from .models import Paciente


class PacienteForm(UtilForm):
    autofocus_field = 'nombre'

    class Meta:
        model = Paciente
        fields = '__all__'

src/paciente/views.py
from django.urls import reverse_lazy

from utils.views import UtilListView, UtilDeleteView, UtilCreateView, UtilUpdateView
from django_filters.views import FilterView

from . import forms, models, tables, search


class ListView(FilterView, UtilListView):
    template_name = 'paciente/list.html'
    table_class = tables.PacienteTable
    paginate_by = 20
    model_class = models.Paciente
    required_permissions = ('paciente.view_paciente',)
    change_permission = 'paciente.change_paciente'
    delete_permission = 'paciente.delete_paciente'
    filterset_class = search.SearchRegionForm


class CreateView(UtilCreateView):
    template_name = 'paciente/create.html'
    model = models.Paciente
    form_class = forms.PacienteForm
    success_url = reverse_lazy('paciente:paciente_list')
    success_message = 'Paciente creada exitosamente'
    required_permissions = ('paciente.add_paciente',)


class UpdateView(UtilUpdateView):
    template_name = 'paciente/update.html'
    model = models.Paciente
    form_class = forms.PacienteForm
    success_url = reverse_lazy('paciente:paciente_list')
    success_message = 'Paciente actualizada exitosamente.'
    required_permissions = ('paciente.change_region',)


class DeleteView(UtilDeleteView):
    template_name = 'paciente/confirm_delete.html'
    model = models.Paciente
    success_url = reverse_lazy('paciente:paciente_list')
    success_message = 'Paciente eliminada exitosamente'
    required_permissions = ('paciente.delete_region',)

src/paciente/templates/paciente/list.html
{% extends "adminlte/base.html" %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="wrapper wrapper-content animated fadeInRight">
    <div class="filter-header well clearfix">
      <h4 style="margin-top: 0">Filtrar</h4>
      {% include "_filter_fields.html" with filter=filter.form %}
      {% if perms.paciente.add_paciente %}
      <div class="row">
        <div class="col-md-12 pull-right">
          <a href="{% url 'paciente:paciente_create' %}" class="btn btn-info pull-right">
            <i class="fa fa-plus" aria-hidden="true"></i> Nuevo Paciente
          </a>
        </div>
      </div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Listado de Pacientes</h5>
          </div>
          <div class="ibox-content">
            {% render_table table %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}